<<<<<<< HEAD
/// <reference types="nativewind/types" />
=======
/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
>>>>>>> 853a62c1ccf16ba9c270e8f28a69449a506fc02f
